services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: database
    depends_on:
      - database

  database:
    image: postgres:latest
    volumes:
      - sql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

volumes:
  sql-data:
